### ISSUE TITLE
Move unit.rs into separate crate?

### ISSUE THREAD

**Issue by pepyakin** [fitzgen/wee_alloc#12]
Maybe a weird idea, but what do you think about

### Summary

Move [units.rs](https://github.com/fitzgen/wee_alloc/blob/master/wee_alloc/src/units.rs) to separate crate and publish it on crates.io?

### Motivation

I came up with that idea when I was working on wasmi. I noticed that Pages→Bytes and Bytes→Pages are quite common thing that people want to do, when working with parity-wasm/wasmi.
Example [here](https://github.com/tailhook/verwalter/blob/82d16ad9b86a1cdf8b7018c1f084f142cc09d902/src/daemon/scheduler/wasm.rs#L105) and [there](https://github.com/paritytech/wasm-utils/blob/81e53080d3490eb742fd56ab58f5f50c5bc41d01/build/src/main.rs#L141).

### Details

I think just taking `units.rs` and moving it into another crate will be enough.
I'm ready to take this if we agree if this idea is worth it.

**Comment by fitzgen** [comment]
I wonder if it already exists? I know there are crates for inches and centimeters, etc.

If a crate already exists,  I'd be happy to switch as long as it seems like a good crate. I also think it is important that rounding up units is *not* an `Into` or `From` impl, since it would make it easy to accidentally do multiple roundings.

If a crate does not exist, I'd be happy to spin `unit.rs` off into its own crate.

We should, of course, verify that code size and performance don't regress.

I'll assign the issue to you :)

**Comment by pepyakin** [comment]
> We should, of course, verify that code size and performance don't regress.

Ah, I just realized that non-LTO linking might inhibit some optimizations that, yeah. 

> I also think it is important that rounding up units is not an Into or From impl, since it would make it easy to accidentally do multiple roundings.

Yeah, agree!

> I wonder if it already exists?

I dunno ¯\_(ツ)_/¯ if I can't find it on crates.io can we assume that such crate doesn't exists?

So if yes, then where should I create the crate, in this repo? In dedicated repo? Do you have ideas about the name?

**Comment by fitzgen** [comment]
I think `#[inline]` should make LTO unnecessary. These are all being inlined anyways right now. Un-inlining them would probably blow up code size, because their bodies are so small that the prolog and epilog is likely bigger.

I can't find such a crate from a few cursory searches on crates.io -- if you can't either, then we can assume one isn't published.

Happy to put it in this repo. Also happy with another repo. Doesn't matter too much to me.

**Comment by fitzgen** [comment]
Maybe `memory_units` is a good name?

**Comment by pepyakin** [comment]
Oh, maybe we thinking about different things. I thought about extracting units as specialized version to wasm (thus PAGE_SIZE should be inside the crate)!

**Comment by fitzgen** [comment]
I thought you were proposing to move all of

* `Bytes`, `Words`, `Pages` type definitions
* `PAGE_SIZE` constant
* `fn size_of<T>() -> Bytes`
* Conversions and `RoundUpTo`

into a separate crate.

Is that not the case?

As far as being specific to wasm or not, the only thing that isn't portable is the `PAGE_SIZE` constant, which can be `#[cfg]`ed pretty easily, I think.

**Comment by pepyakin** [comment]
Yep, that is the case! But I'm not sure how to hide `PAGE_SIZE` under `cfg`...

**Comment by fitzgen** [comment]
Something like

```rust
const WASM_PAGE_SIZE: Bytes = Bytes(...);

#[cfg(target_arch = "wasm32")]
const PAGE_SIZE: Bytes = WASM_PAGE_SIZE;

#[cfg(not(target_arch = "wasm32"))]
const PAGE_SIZE: Bytes = Bytes(4096);
```

?

This would allow access to the wasm page size even when not targeting wasm.

**Comment by pepyakin** [comment]
Ah, this will work, but only for systems with 4096 bytes page size (is there actually systems with non 4k?)

anyway, I think this is good enough for the start, and then `memory_units` makes sense to me

**Comment by fitzgen** [comment]
> Ah, this will work, but only for systems with 4096 bytes page size (is there actually systems with non 4k?)

There are "huge pages" on linux (2G), but you have to go out of your way to use them, and you would be cognizant of their use if you did. I think adding a doc comment that says as much would be fine.

**Comment by pepyakin** [comment]
I've created a new repo!

https://github.com/pepyakin/memory_units

It seems that the size didn't regressed

```
     757 ../target/wasm32-unknown-unknown/release/wee_alloc_example.gc.opt.wasm
    1263 ../target/wasm32-unknown-unknown/release/wee_alloc_example.size_classes.gc.opt.wasm
    2020 total
```

**Comment by pepyakin** [comment]
I stumbled upon a problem: for the use-case when one wants to use `memory_units` in the host side when writing host bindings for wasm embedding, one still wants `PAGE_SIZE` to be 64k, however, because user in host context (e.g. target_arch ≠ wasm32) page size will be 4k.

**Comment by fitzgen** [comment]
Awesome!

> I stumbled upon a problem: for the use-case when one wants to use memory_units in the host side when writing host bindings for wasm embedding, one still wants PAGE_SIZE to be 64k, however, because user in host context (e.g. target_arch ≠ wasm32) page size will be 4k.

Maybe a cargo feature to force the use of wasm units?

> memory_units is primarily distributed under the terms of both the MIT license and the Apache License (Version 2.0), at your choice.

This should actually be licensed under the MPL-2.0, like `wee_alloc` is.

The reason I chose MPL-2.0 is because it lets people do most anything that MIT/Apache do, except if they make changes to any `wee_alloc` source files, then those modified source files must also be released as MPL-2.0. I find it a sweet spot on the spectrum between hard-line copyleft of the GPL family and MIT/BSD which let others profit from our work without contributing back in any way.

**Comment by pepyakin** [comment]
> This should actually be licensed under the MPL-2.0, like wee_alloc is.

I think, I have no problems with it.

> Maybe a cargo feature to force the use of wasm units?

Yeah that will work, but tbh I think that's clumsy.

**Comment by pepyakin** [comment]
Yeah, I think that thing https://github.com/pepyakin/memory_units/pull/1 should work really well!

**Comment by fitzgen** [comment]
Care to make a pr to make wee_alloc use that crate now?

**Comment by pepyakin** [comment]
yeah, definitely! but at some point later
